version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
  mongodb:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_DATABASE: sample
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-Pass@word}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"