export const FIELD_TYPE = {
    COLUMN_BREAK: "Column Break",
    SECTION_BREAK: "Section Break",
    TAB_BREAK: "Tab Break",
    AUTOCOMPLETE: "Autocomplete",
    ATTACH: "Attach",
    ATTACH_IMAGE: "Attach Image",
    BARCODE: "Barcode",
    BUTTON: "Button",
    CHECK: "Check",
    CODE: "Code",
    COLOR: "Color",
    CURRENCY: "Currency",
    DATA: "Data",
    DATE: "Date",
    DATETIME: "Datetime",
    DURATION: "Duration",
    DYNAMIC_LINK: "Dynamic Link",
    FLOAT: "Float",
    GEOLOCATION: "Geolocation",
    HEADING: "Heading",
    HTML: "HTML",
    HTML_EDITOR: "HTML Editor",
    ICON: "Icon",
    IMAGE: "Image",
    INT: "Int",
    JSON: "JSON",
    LINK: "Link",
    LONG_TEXT: "Long Text",
    MARKDOWN_EDITOR: "Markdown Editor",
    PASSWORD: "Password",
    PERCENT: "Percent",
    PHONE: "Phone",
    READ_ONLY: "Read Only",
    RATING: "Rating",
    SELECT: "Select",
    SIGNATURE: "Signature",
    SMALL_TEXT: "Small Text",
    TABLE: "Table",
    TABLE_MULTISELECT: "Table MultiSelect",
    TEXT: "Text",
    TEXT_EDITOR: "Text Editor",
    TIME: "Time",
}