/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';

export type { AuditableEntity } from './models/AuditableEntity';
export type { AuditableEntityOfGuid } from './models/AuditableEntityOfGuid';
export type { AuditDto } from './models/AuditDto';
export type { BaseEntityOfGuid } from './models/BaseEntityOfGuid';
export type { BaseFilter } from './models/BaseFilter';
export type { BrandDto } from './models/BrandDto';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export type { ChartSeries } from './models/ChartSeries';
export type { CreateBrandRequest } from './models/CreateBrandRequest';
export type { CreateDoctypeRequest } from './models/CreateDoctypeRequest';
export type { CreateFieldRequest } from './models/CreateFieldRequest';
export type { CreateOrUpdateRoleRequest } from './models/CreateOrUpdateRoleRequest';
export type { CreateProductRequest } from './models/CreateProductRequest';
export type { CreateTenantRequest } from './models/CreateTenantRequest';
export type { CreateUserRequest } from './models/CreateUserRequest';
export type { DoctypeDto } from './models/DoctypeDto';
export type { DocTypes } from './models/DocTypes';
export type { DomainEvent } from './models/DomainEvent';
export type { ErrorResult } from './models/ErrorResult';
export type { ExportFieldRequest } from './models/ExportFieldRequest';
export type { ExportProductsRequest } from './models/ExportProductsRequest';
export type { FieldDetailsDto } from './models/FieldDetailsDto';
export type { FieldDto } from './models/FieldDto';
export type { FileUploadRequest } from './models/FileUploadRequest';
export type { Filter } from './models/Filter';
export type { ForgotPasswordRequest } from './models/ForgotPasswordRequest';
export type { GenerateRandomBrandRequest } from './models/GenerateRandomBrandRequest';
export type { GenerateRandomDoctypeRequest } from './models/GenerateRandomDoctypeRequest';
export type { HttpValidationProblemDetails } from './models/HttpValidationProblemDetails';
export type { PaginationFilter } from './models/PaginationFilter';
export type { PaginationResponseOfBrandDto } from './models/PaginationResponseOfBrandDto';
export type { PaginationResponseOfDoctypeDto } from './models/PaginationResponseOfDoctypeDto';
export type { PaginationResponseOfFieldDto } from './models/PaginationResponseOfFieldDto';
export type { PaginationResponseOfProductDto } from './models/PaginationResponseOfProductDto';
export type { ProblemDetails } from './models/ProblemDetails';
export type { ProductDetailsDto } from './models/ProductDetailsDto';
export type { ProductDto } from './models/ProductDto';
export type { RefreshTokenRequest } from './models/RefreshTokenRequest';
export type { ResetPasswordRequest } from './models/ResetPasswordRequest';
export type { RoleDto } from './models/RoleDto';
export type { Search } from './models/Search';
export type { SearchBrandsRequest } from './models/SearchBrandsRequest';
export type { SearchDoctypeRequest } from './models/SearchDoctypeRequest';
export type { SearchFieldRequest } from './models/SearchFieldRequest';
export type { SearchProductsRequest } from './models/SearchProductsRequest';
export type { StatsDto } from './models/StatsDto';
export type { TenantDto } from './models/TenantDto';
export type { ToggleUserStatusRequest } from './models/ToggleUserStatusRequest';
export type { TokenRequest } from './models/TokenRequest';
export type { TokenResponse } from './models/TokenResponse';
export type { UpdateBrandRequest } from './models/UpdateBrandRequest';
export type { UpdateDoctypeRequest } from './models/UpdateDoctypeRequest';
export type { UpdateFieldRequest } from './models/UpdateFieldRequest';
export type { UpdateProductRequest } from './models/UpdateProductRequest';
export type { UpdateRolePermissionsRequest } from './models/UpdateRolePermissionsRequest';
export type { UpdateUserRequest } from './models/UpdateUserRequest';
export type { UpgradeSubscriptionRequest } from './models/UpgradeSubscriptionRequest';
export type { UserDetailsDto } from './models/UserDetailsDto';
export type { UserRoleDto } from './models/UserRoleDto';
export type { UserRolesRequest } from './models/UserRolesRequest';

export * as BrandsService from './services/BrandsService';
export * as DashboardService from './services/DashboardService';
export * as DoctypesService from './services/DoctypesService';
export * as FieldsService from './services/FieldsService';
export * as PersonalService from './services/PersonalService';
export * as ProductsService from './services/ProductsService';
export * as RolesService from './services/RolesService';
export * as TenantsService from './services/TenantsService';
export * as TokensService from './services/TokensService';
export * as UsersService from './services/UsersService';
